# Generated by Django 4.2.5 on 2023-10-06 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formasticApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form_13',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('Q10', models.CharField(default='')),
                ('Question_11', models.DateField()),
                ('2', models.CharField(default='')),
                ('Sect_2_question_13', models.CharField(default='')),
            ],
            options={
                'verbose_name': 'New Form Response',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
    ]
