# Generated by Django 4.2.5 on 2023-10-06 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formasticApp', '0002_form_13_alter_user_is_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Form_13',
        ),
    ]
