# Generated by Django 4.2.5 on 2023-10-06 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formasticApp', '0004_form_13'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Form_13',
        ),
    ]
