# Generated by Django 4.2.5 on 2023-10-06 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formasticApp', '0009_form_16'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Form_13',
        ),
        migrations.DeleteModel(
            name='Form_16',
        ),
    ]
