# Generated by Django 4.2.5 on 2023-10-06 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formasticApp', '0010_delete_form_13_delete_form_16'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form_22',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('This_is_Question_10', models.CharField()),
                ('Hello_jee1', models.CharField()),
                ('Section_2_Q_12', models.CharField()),
            ],
        ),
    ]
