# Generated by Django 4.2.5 on 2023-10-06 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formasticApp', '0011_form_22'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form_13',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('Q10', models.CharField()),
                ('Question_11', models.DateField()),
                ('This_is_the_3rd_question_man2', models.CharField()),
                ('Sect_2_question_13', models.CharField()),
            ],
        ),
    ]
