# Generated by Django 4.2.5 on 2023-10-07 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formasticApp', '0014_delete_form_13_delete_form_16_delete_form_22'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form_13',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('Q10', models.CharField()),
                ('Question_11', models.DateField()),
                ('This_is_the_3rd_question_man2', models.CharField()),
                ('Sect_2_question_13', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Form_16',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('Hello_0', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Form_22',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('This_is_Question_10', models.CharField()),
                ('Hello_jee1', models.CharField()),
                ('Section_2_Q_12', models.CharField()),
            ],
        ),
    ]
