# Generated by Django 4.2.5 on 2023-10-12 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formasticApp', '0015_form_13_form_16_form_22'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Form_16',
        ),
    ]
